
import { GoogleGenAI } from "@google/genai";
import { GEMINI_MODEL } from "../constants";

const getAiClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found");
  }
  return new GoogleGenAI({ apiKey });
};

/**
 * Edits an image using Gemini 2.5 Flash Image.
 * Takes a base64 image and a text prompt.
 */
export const editImageWithGemini = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  try {
    const ai = getAiClient();

    // Remove header if present (e.g., "data:image/png;base64,")
    const cleanBase64 = base64Image.split(',')[1] || base64Image;

    const response = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png', // Assuming PNG for simplicity, usually safe for uploaded blobs converted
              data: cleanBase64,
            },
          },
          {
            text: `Edit this image. ${prompt}. Return ONLY the image data.`,
          },
        ],
      },
    });

    // Check for image in response
    // The response structure for image generation/editing usually contains inlineData in the parts
    const parts = response.candidates?.[0]?.content?.parts;
    
    if (parts) {
        for (const part of parts) {
            if (part.inlineData && part.inlineData.data) {
                return `data:image/png;base64,${part.inlineData.data}`;
            }
        }
    }

    throw new Error("No image generated by Gemini.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to edit image");
  }
};

/**
 * Generates a new image using Gemini.
 */
export const generateImageWithGemini = async (prompt: string): Promise<string> => {
  try {
    const ai = getAiClient();

    // Per documentation, use generateContent for nano banana series models
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', 
      contents: {
        parts: [
          {
            text: `Generate an image of: ${prompt}`,
          },
        ],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;

    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by Gemini.");
  } catch (error: any) {
    console.error("Gemini Image Generation Error:", error);
    throw new Error(error.message || "Failed to generate image");
  }
};
